#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://3.235.31.229/   --> returns string "Hello World!"
#	   curl http://3.235.31.229/   --> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
