#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://3.235.31.229/   --> returns string "Hello World!"
#	   curl http://3.235.31.229/   --> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo ufw enable
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
