#!/usr/bin/env bash
# Configure server with: HAproxy version 1.5 or greater
# Distributes request using roundrobin; sends traffic to servers: web-01 and web-02

CFG="\\\n#HAproxy for web servers\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\toption forwardfor\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 19249-web-01 34.204.201.220:80 check\n\tserver 19249-web-02 35.170.76.215:80 check\n"

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get install -y haproxy=2.4\*

# Make sure HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure to include roundrobin and two servers
sudo sed -i "\$a $CFG" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
