#!/usr/bin/env bash
# This script read the file and manipulate it content to generate story
# using a defined format 

FILE="/etc/passwd"

while IFS=":" read -r user pw uid gid uinfo homedir shell
do
    echo "The user $user is part of the $gid gang, lives in $homedir and \
rides $shell. $uid's place is protected by the passcode $pw, \
more info about the user here: $uinfo"
done < "$FILE"
