#!/usr/bin/env bash
# Prints "Best School" for other iteration,
# "bad luck" at 4th loop, "good luck" at 8th loop

i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]; then
	echo "bad luck"
    elif [ "$i" -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
