#!/usr/bin/env bash
# Prints 1 to 20; "bad luck from China" at 4th loop,
# "bad luck from Japan" at 9th loop,
# and "bad luck from Italy" at 17th loop

i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( i++ ))
done
